# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2af5e75d12d059ecc26536d8087dae77d2830fbbd862d2eea8f090910ae2232ae6fef472f4c7d74b390efd9c74f9dff9b24c437f9168c86a390905f3dce6a82

test:
  secret_key_base: d8bfef42cb688615a20c076aebca22521f0d12c65de2a7f1212bdff18fb8a05d33275ccb3e588edaf365a56923091d5ac427d98893651e8e740d5820be4e0420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
